- name: Install all required dependencies
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb